### ISSUE TITLE
Property (_PointLights) at kernel index (0) is not set

### ISSUE THREAD

**Issue by DevCas1** [Unity-Technologies/VolumetricLighting#24]
So, no matter which scene I open, the editor keeps throwing this error.
Also, the lights do not have that amazing volumetric effect at all...

Error occurs on the InjectLightingAndDensity compute shader

Tested on Unity 2018.1.0b12

**Comment by Baccanno** [comment]
Did you try not to update the API and keep the one from 2017.4?  InjectLightingAndDensity comes from the API updater

**Comment by skaale** [comment]
also have same problem in 2018.20b2 any workaround ?

**Comment by marcouberti** [comment]
Same issue here: Mac OS, Unity 2018.1.0f2 personal.

`Property (_PointLights) at kernel index (0) is not set`

**Comment by robertcupisz** [comment]
Fixed!

**Comment by Galaxxxy60** [comment]
FIxed ? really? i still have the issue ...

**Comment by robertcupisz** [comment]
@Galaxxxy60 What error message are you seeing exactly? And in which test scene?

**Comment by Galaxxxy60** [comment]
Hello, 
when i switched to  Unity 2018.1.0b12 from 2017 I get this error :
"Property (_AreaLightShadowmap) at kernel index (0) is not set" in all my scenes with fog...
Recently i saw that the GitHub was updated so i deleted the file in my project to replace it with the new one, but i still have the same error popping up...

ty for your support

**Comment by Galaxxxy60** [comment]
Do I need to update to 2018.2.0f1?

**Comment by sanmn19** [comment]
Still facing it in 2018.2.0f1 and 2018.1.1f1 with error "Property (_SourcePos) at kernel index (0) is not set
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()"

**Comment by maxsamarin** [comment]
Still facing in 2018.2.8f1

Compute shader (InjectLightingAndDensity): Property (_AreaLightShadowmap) at kernel index (0) is not set
